### ISSUE TITLE
Issue using res/values/strings.xml for the key

### ISSUE THREAD

**Issue by alamboley** [BranchMetrics/Branch-Android-SDK#65]
Hey, I'm working on an Air Native Extensions for Branch io, basically it's a bridge between AS3 and your Java SDK.

Unfortunately, I'm not able to use the res/values/strings.xml with an ANE, however I've access to the Manifest.xml
Does the key could be setup directly in the Manifest? Why do you use the res/values/strings.xml ?

Here is an example of Google Play Games ' key set directly in the Manifest: `<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ aKey" />`

**Comment by qinweigong** [comment]
Hi @alamboley ,

Thanks a lot for your feedback! And seems you are right!

I actually tried this approach couple months back, but at that time it didn't seem to work. Anyway, I will have more tests and will simplify like this if everything is fine.

Again, thanks a lot and really appreciate your support for Branch!

Qinwei

**Comment by qinweigong** [comment]
@alamboley OK, I know what was going on!
We used to use the app key as the API key for initializing the Branch object as well as performing all the API calls. That app key is essentially an integer. When put in Manifest directly, even if double quoted, I would still get runtime error like below:

`<meta-data android:name="io.branch.sdk.ApplicationId" android:value="5668720416392048" />`
```
Key io.branch.sdk.ApplicationId expected String but value was a java.lang.Integer.  The default value <null> was returned.
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
at android.os.Bundle.getString(Bundle.java:1121)
```
That's why I had to specify it indirectly via the strings.xml file!

However, we replaced the app key with our new Branch key, which is no longer a pure integer but a String. Hence, we can put it in Manifest directly now! :-)

Thanks so much for bringing this to us! Without your reminder, I probably won't be thinking of making this change any time soon. Though only one less step, it actually greatly simplifies our onboarding process for Android users!

We will update our README/tutorials/references/guides today or tomorrow, as well as our TestBed project. For now, you can just go ahead and specify your Branch key in your manifest like below:
`<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_yourbranchkey" />`

**Comment by alamboley** [comment]
Awesome, thanks! :+1:
